### ISSUE TITLE
Sliders Only Update For Player Input

### ISSUE THREAD

**Issue by lmarren1** [lmarren1/nba-threes-since-1979#1]
#### Description
When a user inputs a value range for all sliders *except* `input$player` (or "Player(s) Selected" in the UI), the other sliders do not update accordingly. I.e., there are no cross-dependencies on for the input sliders aside from the player input.

#### Screenshot of Issue
<img width="934" alt="Screenshot 2023-12-20 123541" src="https://github.com/lmarren1/nba-threes-since-1979/assets/104032853/8441b071-952a-4975-ae5b-75cfcb56dfe2">

Notice how when `3-Point Makes (By Game)` is incremented to 10 `3-Point Attempts (By Game)` (and other relevant sliders) does not update to at least 10.

#### Files
The issue has to do with the [app.R](app.R) file.

#### Tasks
The following tasks should be completed in order to solve the issue:
- [ ] Task 1 - Create `observeEvent()` expressions with the `eventExpr`'s individually equal to: `dateGame_input`, `game_fg3a_input`, `game_fg3m_input`, `season_fg3a_input`, `season_fg3m_input`, `career_fg3a_input`, `career_fg3m_input`, `season_pctFG3_input`.
- [ ] Task 2 - Add `handlerExpr`'s including the relevant `Shiny` "update input" functions to the `observeEvent` expressions. E.g., when `game_fg3m_input` is changed by the user, `game_fg3a_input`'s, and `career_fg3a_input`'s and `career_fg3m_input`'s ranges should change accordingly.
- [ ]  Task 3 - Ensure the Shiny app still runs successfully and updates inputs/outputs as desired.
